name: CI # Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Docker Version
        run: docker --version
      - name: build
        run: docker build --build-arg SCRIPT_ARG=abc -t myapp .
      - name: run
        run: docker run myapp
