name: CI # Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Docker Version
        run: docker --version
#       - name: Install Latest Docker
#         run: |
#           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#           sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
#           sudo apt-get update
#           sudo apt-get install docker-ce
#       - name: Check Docker Version
#         run: docker --version
      - name: build
        run: docker build --build-arg SCRIPT_ARG=abc -t myapp .
      - name: run
        run: docker run myapp
