name: CI # Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build
        run: docker build -t myapp .
      - name: run
        run: docker run myapp
